services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 80:80
    depends_on:
      - app
    container_name: app_nginx

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/
    depends_on:
      - db
      - redis
    container_name: app

  db:
    image: mysql:latest
    restart: always
    volumes:
      - ./_docker/temp/db/:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    container_name: app_db

  redis:
    image: redis:7.4.1
    ports:
      - 6379:6379
    container_name: app_redis

  node:
    image: node:20.12
    volumes:
      - ./:/var/www/
    working_dir: /var/www
    command: bash -c "npm install && npm run dev"
    ports:
      - 3000:3000
    tty: true
    container_name: app_node
